services:
  db:
    image: postgres:16
    container_name: blackbank-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blackbank
    ports:
      - "5433:5432"
    volumes:
      - blackbank_db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: blackbank-api
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/blackbank
      JWT_SECRET: supersecret_jwt_key
    depends_on:
      - db
    ports:
      - "3000:3000"

  api-dev:
    image: node:lts
    container_name: blackbank-api-dev
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/blackbank
      JWT_SECRET: supersecret_jwt_key
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - dev

volumes:
  blackbank_db_data:

